name: we_talk
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+2

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.0.1

  #for accessing firebase storage and uploading images
  firebase_storage: ^12.0.1

  #for picking image from gallery
  image_picker: ^1.1.2
  gallery_picker: ^0.5.1

  # for image processing package for profile and other stuffs
  cached_network_image: ^3.3.1

  #for compressing the image to store database
  flutter_image_compress: ^2.3.0

  #for cropping profile image
  image_cropper: ^7.0.4

  #for emoji picker
  emoji_picker_flutter: ^2.2.0

  #for saving image into  our gallery
  gallery_saver_updated: ^3.0.0

  #for push notification
  firebase_messaging: ^15.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

    #for changing the application icon
#   flutter_launcher_icons: "^0.13.1"

# flutter_launcher_icons:
#   android: "ic_launcher"
#   ios: true
#   image_path: "images/chat_app3.png"
#   min_sdk_android: 21 
  
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
